/**
 * Plan validation shared by generation, repair and refinement.
 *
 * The rules live once, in PLAN_VALIDATOR_SCRIPT: a dependency-free Node script
 * that agents run inside their workspace while they write or repair a plan,
 * and that ProPR runs again on the result, on fresh copies of the script and
 * the original, so an agent cannot pass by editing either.
 */

import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

const execFileAsync = promisify(execFile);

export const PLAN_FILE = 'plan.json';
export const PLAN_ORIGINAL_FILE = 'original.txt';
export const PLAN_VALIDATOR_FILE = 'validate-plan.mjs';
/** Incremental contract: one task object per file, assembled in file-name order. */
export const PLAN_TASKS_DIR = 'tasks';

/**
 * Positions (1-based) of plan items that are not complete issues: a model
 * sometimes returns edit instructions ("retain issue 3") or partial issues.
 */
export function incompletePlanItems(plan: unknown[]): number[] {
  const incomplete: number[] = [];
  plan.forEach((item, index) => {
    const record = item && typeof item === 'object' ? item as Record<string, unknown> : null;
    const complete = !!record && (['title', 'body', 'implementation'] as const)
      .every(field => typeof record[field] === 'string' && (record[field] as string).trim().length > 0);
    if (!complete) incomplete.push(index + 1);
  });
  return incomplete;
}

/**
 * The JSON array in a model response, without surrounding code fences or
 * prose, or null when the response does not hold a whole array. A response
 * that starts or ends mid-array is a fragment: repairing it would silently
 * drop the missing tasks, so it must fail instead.
 */
export function extractWholeJsonArray(response: string): string | null {
  const fenced = response.match(/```(?:json)?\s*\n([\s\S]*?)\n\s*```/);
  const text = (fenced ? fenced[1] : response).trim();
  const start = text.indexOf('[');
  const end = text.lastIndexOf(']');
  if (start === -1 || end <= start) return null;
  // Only prose may precede the array: a fragment that begins inside an object
  // (`"key": ...` or `{`) is not a whole plan.
  const prefix = text.slice(0, start);
  if (/[{}"]/.test(prefix)) return null;
  const array = text.slice(start, end + 1);
  return /^\[\s*\{/.test(array) ? array : null;
}

/**
 * Standalone validator. `node validate-plan.mjs [plan.json] [original.txt]`
 * prints a JSON report and exits 0 only when the plan is valid. With
 * `--tasks <dir>` it first assembles `<dir>/*.json`, one task object per file
 * in file-name order, into plan.json, so a plan too large for one message can
 * be written task by task. With an
 * original present it also proves that the plan keeps the original's content:
 * every text appears in the original and nearly all of it is accounted for, so
 * a repair can fix syntax but cannot reword, drop or invent tasks.
 */
export const PLAN_VALIDATOR_SCRIPT = String.raw`#!/usr/bin/env node
// Validates a ProPR plan. Do not edit this file: ProPR re-runs its own copy.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const tasksFlag = args.indexOf('--tasks');
const tasksDir = tasksFlag === -1 ? null : (args.splice(tasksFlag, 2)[1] || 'tasks');
const planPath = args[0] || 'plan.json';
const originalPath = args[1] || 'original.txt';
const REQUIRED = ['title', 'body', 'implementation'];
const errors = [];
let taskFiles = [];
let plan;

if (tasksDir !== null) {
  taskFiles = existsSync(tasksDir) ? readdirSync(tasksDir).filter(name => name.endsWith('.json')).sort() : [];
  if (taskFiles.length === 0) errors.push('no task files: write one task object per file as ' + tasksDir + '/001.json, ' + tasksDir + '/002.json, ...');
  const tasks = [];
  for (const name of taskFiles) {
    try {
      const task = JSON.parse(readFileSync(tasksDir + '/' + name, 'utf8'));
      if (Array.isArray(task)) errors.push(tasksDir + '/' + name + ' must hold one task object, not an array');
      else tasks.push(task);
    } catch (error) {
      errors.push(tasksDir + '/' + name + ' is not valid JSON: ' + error.message);
    }
  }
  if (errors.length === 0) writeFileSync(planPath, JSON.stringify(tasks, null, 2) + '\n');
}
const label = index => 'task ' + (index + 1) + (taskFiles[index] ? ' (' + tasksDir + '/' + taskFiles[index] + ')' : '');

if (errors.length === 0) {
  try {
    plan = JSON.parse(readFileSync(planPath, 'utf8'));
  } catch (error) {
    errors.push(planPath + ' is not valid JSON: ' + error.message);
  }
}

if (plan !== undefined) {
  if (!Array.isArray(plan)) errors.push(planPath + ' must contain a JSON array of tasks');
  else if (plan.length === 0) errors.push('the plan has no tasks');
  else plan.forEach((task, index) => {
    if (!task || typeof task !== 'object' || Array.isArray(task)) {
      errors.push(label(index) + ' is not an object');
      return;
    }
    for (const field of REQUIRED) {
      if (typeof task[field] !== 'string' || !task[field].trim()) {
        errors.push(label(index) + ' has no non-empty "' + field + '" string');
      }
    }
  });
}

if (errors.length === 0 && existsSync(originalPath)) {
  // Compare content, not syntax: decode JSON escapes, then ignore whitespace,
  // quotes and backslashes, which is exactly what a syntax repair may change.
  const decode = text => text
    .replace(/\\u([0-9a-fA-F]{4})/g, (_, hex) => String.fromCharCode(parseInt(hex, 16)))
    .replace(/\\(["\\/bfnrt])/g, (_, c) => ({ b: '', f: '', n: '\n', r: '\r', t: '\t' })[c] ?? c);
  const normalize = text => text.replace(/[\s"\\]/g, '');
  const original = readFileSync(originalPath, 'utf8');
  const source = normalize(decode(original));
  let kept = 0;
  plan.forEach((task, index) => {
    for (const [field, value] of Object.entries(task)) {
      if (typeof value !== 'string') continue;
      const text = normalize(value);
      kept += text.length;
      if (text && !source.includes(text)) {
        errors.push(label(index) + ' "' + field + '" does not match ' + originalPath + ': fix syntax only, never reword content');
      }
    }
  });
  const originalTasks = (original.match(/"title"\s*:/g) || []).length;
  if (plan.length < originalTasks) {
    errors.push(originalPath + ' has ' + originalTasks + ' tasks but ' + planPath + ' has ' + plan.length + ': keep every task');
  }
  // Keys, braces and commas are the only content a repair may leave out.
  const missing = source.length - kept;
  if (missing > 80 * plan.length + 300) {
    errors.push(planPath + ' is missing about ' + missing + ' characters of ' + originalPath + ' content: keep every task and field');
  }
}

const report = { valid: errors.length === 0, taskCount: Array.isArray(plan) ? plan.length : 0, errors };
console.log(JSON.stringify(report, null, 2));
process.exit(report.valid ? 0 : 1);
`;

export interface PlanValidationReport {
  valid: boolean;
  taskCount: number;
  errors: string[];
}

async function runOwnValidator(directory: string, args: string[]): Promise<PlanValidationReport> {
  await writeFile(path.join(directory, PLAN_VALIDATOR_FILE), PLAN_VALIDATOR_SCRIPT);
  const { stdout } = await execFileAsync(process.execPath, [PLAN_VALIDATOR_FILE, ...args], {
    cwd: directory, timeout: 30_000, maxBuffer: 1024 * 1024,
  }).catch((error: { stdout?: string; message: string }) => {
    if (typeof error.stdout === 'string' && error.stdout.trim()) return { stdout: error.stdout };
    throw error;
  });
  return JSON.parse(stdout) as PlanValidationReport;
}

/**
 * Validates plan text with ProPR's own copy of the validator, in a private
 * directory, so a workspace's (possibly edited) validator is never trusted.
 */
export async function validatePlanText(planText: string, original?: string): Promise<PlanValidationReport> {
  const directory = await mkdtemp(path.join(tmpdir(), 'propr-plan-validate-'));
  try {
    await writeFile(path.join(directory, PLAN_FILE), planText);
    if (original !== undefined) await writeFile(path.join(directory, PLAN_ORIGINAL_FILE), original);
    return await runOwnValidator(directory, [PLAN_FILE, PLAN_ORIGINAL_FILE]);
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}

/**
 * Assembles and validates task files (name → content, one task object each)
 * with ProPR's own validator. Returns the assembled plan text when valid.
 */
export async function validatePlanTaskFiles(taskFiles: Record<string, string>): Promise<PlanValidationReport & { planText: string | null }> {
  const directory = await mkdtemp(path.join(tmpdir(), 'propr-plan-validate-'));
  try {
    await mkdir(path.join(directory, PLAN_TASKS_DIR));
    for (const [name, content] of Object.entries(taskFiles)) {
      if (path.basename(name) !== name || !name.endsWith('.json')) throw new Error(`Invalid task file name: ${name}`);
      await writeFile(path.join(directory, PLAN_TASKS_DIR, name), content);
    }
    const report = await runOwnValidator(directory, ['--tasks', PLAN_TASKS_DIR, PLAN_FILE]);
    const planText = report.valid ? await readFile(path.join(directory, PLAN_FILE), 'utf8') : null;
    return { ...report, planText };
  } finally {
    await rm(directory, { recursive: true, force: true });
  }
}
